TypeError: plugin is not a function     at <unknown> (file:///home/user/studio/.next/server/chunks/ssr/node_modules_4671a859._.js:21715:34)     at Array.forEach (<anonymous>)     at Genkit.configure (file:///home/user/studio/.next/server/chunks/ssr/node_modules_4671a859._.js:21714:17)     at new Genkit (file:///home/user/studio/.next/server/chunks/ssr/node_modules_4671a859._.js:21457:14)     at genkit (file:///home/user/studio/.next/server/chunks/ssr/node_modules_4671a859._.js:21745:12)     at [project]/src/ai/genkit.ts [app-rsc] (ecmascript) (file:///home/user/studio/.next/server/chunks/ssr/[root of the server]__14654dfd._.js:242:162)     at instantiateModule (file:///home/user/studio/.next/server/chunks/ssr/[turbopack]_runtime.js:593:23)     at getOrInstantiateModuleFromParent (file:///home/user/studio/.next/server/chunks/ssr/[turbopack]_runtime.js:652:12)     at esmImport (file:///home/user/studio/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)     at [project]/src/ai/flows/scripture-message-generator.ts [app-rsc] (ecmascript) (file:///home/user/studio/.next/server/chunks/ssr/[root of the server]__14654dfd._.js:263:149)     at instantiateModule (file:///home/user/studio/.next/server/chunks/ssr/[turbopack]_runtime.js:593:23)     at getOrInstantiateModuleFromParent (file:///home/user/studio/.next/server/chunks/ssr/[turbopack]_runtime.js:652:12)     at esmImport (file:///home/user/studio/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)     at [project]/.next-internal/server/app/scripture-generator/page/actions.js { ACTIONS_MODULE0 => "[project]/src/ai/flows/scripture-message-generator.ts [app-rsc] (ecmascript)" } [app-rsc] (server actions loader, ecmascript) <module evaluation> (file:///home/user/studio/.next/server/chunks/ssr/[root of the server]__14654dfd._.js:324:181)     at instantiateModule (file:///home/user/studio/.next/server/chunks/ssr/[turbopack]_runtime.js:593:23)     at getOrInstantiateModuleFromParent (file:///home/user/studio/.next/server/chunks/ssr/[turbopack]_runtime.js:652:12)     at esmImport (file:///home/user/studio/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)     at [project]/.next-internal/server/app/scripture-generator/page/actions.js { ACTIONS_MODULE0 => "[project]/src/ai/flows/scripture-message-generator.ts [app-rsc] (ecmascript)" } [app-rsc] (server actions loader, ecmascript) (file:///home/user/studio/.next/server/chunks/ssr/[root of the server]__14654dfd._.js:346:424)     at instantiateModule (file:///home/user/studio/.next/server/chunks/ssr/[turbopack]_runtime.js:593:23)     at instantiateRuntimeModule (file:///home/user/studio/.next/server/chunks/ssr/[turbopack]_runtime.js:660:12)     at Object.getOrInstantiateRuntimeModule (file:///home/user/studio/.next/server/chunks/ssr/[turbopack]_runtime.js:676:12)     at Object.<anonymous> (file:///home/user/studio/.next/server/app/scripture-generator/page.js:29:9)     at Module._compile (node:internal/modules/cjs/loader:1529:14)     at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)     at Module.load (node:internal/modules/cjs/loader:1275:32)     at Module._load (node:internal/modules/cjs/loader:1096:12)     at Module.require (node:internal/modules/cjs/loader:1298:19)     at mod.require (file:///home/user/studio/node_modules/next/dist/server/require-hook.js:65:28)     at require (node:internal/modules/helpers:182:18)     at requirePage (file:///home/user/studio/node_modules/next/dist/server/require.js:103:84)     at loadComponentsImpl (file:///home/user/studio/node_modules/next/dist/server/load-components.js:129:57)     at async DevServer.findPageComponentsImpl (file:///home/user/studio/node_modules/next/dist/server/next-server.js:808:36)     at async DevServer.findPageComponents (file:///home/user/studio/node_modules/next/dist/server/dev/next-dev-server.js:628:16)     at async DevServer.renderPageComponent (file:///home/user/studio/node_modules/next/dist/server/base-server.js:2379:24)     at async DevServer.renderToResponseImpl (file:///home/user/studio/node_modules/next/dist/server/base-server.js:2430:32)     at async DevServer.pipeImpl (file:///home/user/studio/node_modules/next/dist/server/base-server.js:1003:25)     at async NextNodeServer.handleCatchallRenderRequest (file:///home/user/studio/node_modules/next/dist/server/next-server.js:304:17)     at async DevServer.handleRequestImpl (file:///home/user/studio/node_modules/next/dist/server/base-server.js:895:17)     at async (file:///home/user/studio/node_modules/next/dist/server/dev/next-dev-server.js:371:20)     at async Span.traceAsyncFn (file:///home/user/studio/node_modules/next/dist/trace/trace.js:157:20)     at async DevServer.handleRequest (file:///home/user/studio/node_modules/next/dist/server/dev/next-dev-server.js:368:24)     at async invokeRender (file:///home/user/studio/node_modules/next/dist/server/lib/router-server.js:247:21)     at async handleRequest (file:///home/user/studio/node_modules/next/dist/server/lib/router-server.js:438:24)     at async requestHandlerImpl (file:///home/user/studio/node_modules/next/dist/server/lib/router-server.js:462:13)     at async Server.requestListener (file:///home/user/studio/node_modules/next/dist/server/lib/start-server.js:158:13)